(function(){
  var $=function(id){return document.getElementById(id)};
  var canvas=$('board'),ctx=canvas.getContext('2d');
  var state={n:17,maze:[],player:{x:0,y:0},exit:{x:0,y:0},key:null,gems:[],gemTotal:0,traps:[],portals:[],gotKey:false,score:0,level:1,start:0,time:0,timer:null,particles:[],message:'先拿钥匙，再去发光出口。小心红色陷阱！'};
  function rand(n){return Math.floor(Math.random()*n)}
  function shuffle(a){for(var i=a.length-1;i>0;i--){var j=rand(i+1),t=a[i];a[i]=a[j];a[j]=t}return a}
  function cell(x,y){return state.maze[y]&&state.maze[y][x]}
  function openCell(x,y){return cell(x,y)===0}
  function carve(){var n=state.n,m=[];for(var y=0;y<n;y++){m[y]=[];for(var x=0;x<n;x++)m[y][x]=1}function dig(x,y){m[y][x]=0;var dirs=shuffle([[2,0],[-2,0],[0,2],[0,-2]]);for(var i=0;i<dirs.length;i++){var nx=x+dirs[i][0],ny=y+dirs[i][1];if(nx>0&&ny>0&&nx<n-1&&ny<n-1&&m[ny][nx]){m[y+dirs[i][1]/2][x+dirs[i][0]/2]=0;dig(nx,ny)}}}dig(1,1);state.maze=m}
  function empties(){var a=[];for(var y=1;y<state.n-1;y++)for(var x=1;x<state.n-1;x++)if(openCell(x,y)&&(x!==1||y!==1))a.push({x:x,y:y});return shuffle(a)}
  function farthest(){var q=[{x:1,y:1,d:0}],seen={'1,1':1},best=q[0],dirs=[[1,0],[-1,0],[0,1],[0,-1]];for(var qi=0;qi<q.length;qi++){var p=q[qi];if(p.d>best.d)best=p;for(var i=0;i<4;i++){var nx=p.x+dirs[i][0],ny=p.y+dirs[i][1],k=nx+','+ny;if(openCell(nx,ny)&&!seen[k]){seen[k]=1;q.push({x:nx,y:ny,d:p.d+1})}}}return {x:best.x,y:best.y}}
  function newMaze(){state.n=Math.min(25,15+state.level*2);if(state.n%2===0)state.n++;carve();state.player={x:1,y:1};state.exit=farthest();var e=empties();state.key=e.shift();state.gemTotal=Math.min(5,2+state.level);state.gems=e.slice(0,state.gemTotal);state.traps=e.slice(8,8+Math.min(7,2+state.level));state.portals=[e[20]||e[2],e[30]||e[3]];state.gotKey=false;state.start=Date.now();state.time=0;state.message='第 '+state.level+' 关启动：找钥匙、拿宝石、冲出口！';clearInterval(state.timer);state.timer=setInterval(tick,100);renderHud()}
  function tick(){state.time=(Date.now()-state.start)/1000;renderHud()}
  function at(a,x,y){for(var i=0;i<a.length;i++)if(a[i]&&a[i].x===x&&a[i].y===y)return i;return -1}
  function burst(x,y,c){for(var i=0;i<18;i++)state.particles.push({x:x,y:y,dx:(Math.random()-.5)*.16,dy:(Math.random()-.5)*.16,life:24,color:c})}
  function move(dx,dy){var nx=state.player.x+dx,ny=state.player.y+dy;if(!openCell(nx,ny)){state.message='撞墙啦！换条路试试。';renderHud();return}state.player.x=nx;state.player.y=ny;var gi=at(state.gems,nx,ny);if(gi>-1){state.gems.splice(gi,1);state.score+=30;state.message='捡到能量宝石 +30！';burst(nx,ny,'#67e8f9')}if(state.key&&nx===state.key.x&&ny===state.key.y){state.gotKey=true;state.key=null;state.score+=80;state.message='拿到霓虹钥匙！出口已解锁。';burst(nx,ny,'#facc15')}var ti=at(state.traps,nx,ny);if(ti>-1){state.score=Math.max(0,state.score-20);state.start-=3000;state.message='踩到闪电陷阱，扣 3 秒和 20 分！';burst(nx,ny,'#fb7185')}if(state.portals[0]&&nx===state.portals[0].x&&ny===state.portals[0].y){state.player={x:state.portals[1].x,y:state.portals[1].y};state.message='穿过传送门！';burst(nx,ny,'#a78bfa')}else if(state.portals[1]&&nx===state.portals[1].x&&ny===state.portals[1].y){state.player={x:state.portals[0].x,y:state.portals[0].y};state.message='传送成功，位置反转！';burst(nx,ny,'#a78bfa')}if(state.player.x===state.exit.x&&state.player.y===state.exit.y){if(!state.gotKey){state.message='出口锁着，先去找钥匙！'}else{var bonus=Math.max(20,Math.round(180-state.time)*2)+state.gems.length*10;state.score+=bonus;state.message='通关！速度奖励 +'+bonus+'，进入下一关。';burst(nx,ny,'#22c55e');state.level++;setTimeout(newMaze,700)}}renderHud()}
  function renderHud(){$('level').innerHTML=state.level;$('time').innerHTML=state.time.toFixed(1);$('gems').innerHTML=state.gemTotal-state.gems.length;$('gemTotal').innerHTML=state.gemTotal;$('keyState').innerHTML=state.gotKey?'已拿':'未拿';$('score').innerHTML=state.score;$('status').innerHTML=state.message}
  function drawIcon(txt,x,y,size){ctx.font=Math.floor(size*.66)+'px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(txt,x,y)}
  function draw(){var n=state.n,size=canvas.width/n,t=Date.now();ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#050816';ctx.fillRect(0,0,canvas.width,canvas.height);for(var y=0;y<n;y++){for(var x=0;x<n;x++){var px=x*size,py=y*size;if(state.maze[y][x]){ctx.fillStyle='#101936';ctx.fillRect(px,py,size,size);ctx.strokeStyle='rgba(34,211,238,.20)';ctx.strokeRect(px+.5,py+.5,size-1,size-1)}else{ctx.fillStyle='rgba(15,23,42,.78)';ctx.fillRect(px,py,size,size)}}}var pulse=(Math.sin(t/180)+1)/2;ctx.fillStyle='rgba(34,197,94,'+(state.gotKey ? .55 : .18)+')';ctx.fillRect(state.exit.x*size+3,state.exit.y*size+3,size-6,size-6);drawIcon('🚪',state.exit.x*size+size/2,state.exit.y*size+size/2,size);if(state.key)drawIcon('🗝️',state.key.x*size+size/2,state.key.y*size+size/2,size);for(var i=0;i<state.gems.length;i++)drawIcon('💎',state.gems[i].x*size+size/2,state.gems[i].y*size+size/2,size);ctx.fillStyle='rgba(248,113,113,.25)';for(i=0;i<state.traps.length;i++){ctx.fillRect(state.traps[i].x*size+5,state.traps[i].y*size+5,size-10,size-10);drawIcon('⚡',state.traps[i].x*size+size/2,state.traps[i].y*size+size/2,size)}for(i=0;i<state.portals.length;i++){ctx.strokeStyle='rgba(167,139,250,'+(.55+pulse*.35)+')';ctx.lineWidth=3;ctx.beginPath();ctx.arc(state.portals[i].x*size+size/2,state.portals[i].y*size+size/2,size*.32,0,Math.PI*2);ctx.stroke();drawIcon('🌀',state.portals[i].x*size+size/2,state.portals[i].y*size+size/2,size)}var cx=state.player.x*size+size/2,cy=state.player.y*size+size/2;ctx.shadowColor='#22d3ee';ctx.shadowBlur=18;drawIcon('🤖',cx,cy,size);ctx.shadowBlur=0;for(i=state.particles.length-1;i>=0;i--){var p=state.particles[i];p.x+=p.dx;p.y+=p.dy;p.life--;ctx.fillStyle=p.color;ctx.globalAlpha=Math.max(0,p.life/24);ctx.beginPath();ctx.arc(p.x*size+size/2,p.y*size+size/2,3,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;if(p.life<=0)state.particles.splice(i,1)}requestAnimationFrame(draw)}
  document.onkeydown=function(e){var k=e.key||'';if(k==='ArrowUp'||k==='w'||k==='W')move(0,-1);else if(k==='ArrowDown'||k==='s'||k==='S')move(0,1);else if(k==='ArrowLeft'||k==='a'||k==='A')move(-1,0);else if(k==='ArrowRight'||k==='d'||k==='D')move(1,0)};
  $('up').onclick=function(){move(0,-1)};$('down').onclick=function(){move(0,1)};$('left').onclick=function(){move(-1,0)};$('right').onclick=function(){move(1,0)};$('newBtn').onclick=function(){state.level=1;state.score=0;newMaze()};newMaze();draw();
})();
