const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const dist = path.join(root, 'dist');
fs.rmSync(dist, { recursive: true, force: true });
fs.mkdirSync(dist, { recursive: true });
fs.copyFileSync(path.join(root, 'index.html'), path.join(dist, 'index.html'));
fs.copyFileSync(path.join(root, 'src', 'main.js'), path.join(dist, 'snake-ios-v3.js'));
fs.copyFileSync(path.join(root, 'src', 'styles.css'), path.join(dist, 'snake-ios-v3.css'));
console.log('Built classic iOS-compatible static site to dist/');
