(function(){
  var materials={wood:{name:'木质浮箱',rho:.60,color:'#b7791f'},ice:{name:'冰晶舱',rho:.92,color:'#bfdbfe'},plastic:{name:'塑料舱',rho:1.10,color:'#fb923c'},brick:{name:'陶瓷重舱',rho:1.80,color:'#dc2626'},iron:{name:'铁甲舱',rho:7.80,color:'#475569'}};
  var liquids={oil:{name:'油海',rho:.80,color:'rgba(250,204,21,.50)'},water:{name:'清水',rho:1.00,color:'rgba(14,165,233,.46)'},salt:{name:'盐水',rho:1.20,color:'rgba(6,182,212,.52)'},honey:{name:'蜂蜜沼泽',rho:1.40,color:'rgba(245,158,11,.55)'}};
  var levels=[
    {zone:'top',title:'抢救海面补给包',story:'让潜艇漂在水面附近，别沉下去。',mat:'plastic',liq:'water',hollow:20,vol:120},
    {zone:'bottom',title:'潜到海底捡黑匣子',story:'这关需要明显下沉，到底部才算成功。',mat:'brick',liq:'water',hollow:0,vol:140},
    {zone:'middle',title:'悬停扫描珊瑚礁',story:'目标是停在中间区域，太浮或太沉都不行。',mat:'plastic',liq:'salt',hollow:10,vol:110},
    {zone:'top',title:'铁甲潜艇也要浮起来',story:'铁很重，但空心舱可以制造奇迹。',mat:'iron',liq:'honey',hollow:86,vol:200},
    {zone:'middle',title:'蜂蜜沼泽慢速穿越',story:'蜂蜜密度高，找一个接近悬浮的组合。',mat:'brick',liq:'honey',hollow:20,vol:150},
    {zone:'bottom',title:'避开水面风暴',story:'风暴来了，赶紧让潜艇沉到安全深度。',mat:'plastic',liq:'oil',hollow:0,vol:100},
    {zone:'top',title:'盐湖极速救援',story:'盐水浮力更强，利用它快速上浮。',mat:'ice',liq:'salt',hollow:0,vol:130},
    {zone:'middle',title:'终极平衡大师',story:'控制密度比接近 1，完成最稳悬停。',mat:'plastic',liq:'water',hollow:8,vol:160}
  ];
  var state={level:0,score:0,combo:0,time:60,timer:null,started:false,log:[],anim:0,flash:0,lastY:null};
  var $=function(id){return document.getElementById(id)};
  var canvas=$('scene'),ctx=canvas.getContext('2d');
  function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
  function round(n){return Math.round(n*100)/100}
  function params(){var m=materials[$('material').value],l=liquids[$('liquid').value],v=parseInt($('volume').value,10),h=parseInt($('hollow').value,10)/100;var avg=m.rho*(1-h);var ratio=avg/l.rho;var y;if(ratio<.92)y=.18;else if(ratio>1.10)y=.82;else y=.5+(ratio-1)*2.5;return{m:m,l:l,v:v,h:h,avg:avg,ratio:ratio,y:clamp(y,.16,.84)}}
  function targetRange(zone){return zone==='top'?[.13,.31]:zone==='bottom'?[.69,.88]:[.42,.58]}
  function zoneName(z){return z==='top'?'水面区':z==='bottom'?'海底区':'悬浮区'}
  function setPreset(i){var lv=levels[i];$('material').value=lv.mat;$('liquid').value=lv.liq;$('hollow').value=lv.hollow;$('volume').value=lv.vol}
  function stars(){var s=state.score>=520?'★★★':state.score>=340?'★★☆':state.score>=160?'★☆☆':'☆☆☆';$('stars').innerHTML=s}
  function roundRect(c,x,y,w,h,r){c.moveTo(x+r,y);c.lineTo(x+w-r,y);c.quadraticCurveTo(x+w,y,x+w,y+r);c.lineTo(x+w,y+h-r);c.quadraticCurveTo(x+w,y+h,x+w-r,y+h);c.lineTo(x+r,y+h);c.quadraticCurveTo(x,y+h,x,y+h-r);c.lineTo(x,y+r);c.quadraticCurveTo(x,y,x+r,y)}
  function draw(){var p=params(),lv=levels[state.level],r=targetRange(lv.zone),w=canvas.width,h=canvas.height;state.anim++;ctx.clearRect(0,0,w,h);ctx.fillStyle='#ecfeff';ctx.fillRect(0,0,w,h);var tank={x:54,y:64,w:652,h:360},waterY=tank.y+54,waterH=tank.h-8-(waterY-tank.y);ctx.fillStyle='rgba(15,118,110,.08)';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#155e75';ctx.lineWidth=5;ctx.strokeRect(tank.x,tank.y,tank.w,tank.h);ctx.fillStyle=p.l.color;ctx.fillRect(tank.x+3,waterY,tank.w-6,waterH);for(var i=0;i<10;i++){ctx.fillStyle='rgba(255,255,255,.40)';ctx.beginPath();ctx.arc(tank.x+35+i*65,waterY+14+Math.sin((state.anim+i)/10)*5,18,0,Math.PI*2);ctx.fill()}var ty=waterY+r[0]*waterH,th=(r[1]-r[0])*waterH;ctx.fillStyle=lv.zone==='top'?'rgba(34,197,94,.20)':lv.zone==='middle'?'rgba(250,204,21,.24)':'rgba(239,68,68,.18)';ctx.fillRect(tank.x+8,ty,tank.w-16,th);ctx.fillStyle='#0f172a';ctx.font='900 18px sans-serif';ctx.fillText('目标：'+zoneName(lv.zone),tank.x+18,ty+28);var size=54+Math.round((p.v-60)/160*34),x=tank.x+tank.w/2-size/2,y=waterY+p.y*waterH-size/2+Math.sin(state.anim/10)*3;if(state.lastY!==null)y=state.lastY+(y-state.lastY)*.12;state.lastY=y;ctx.save();ctx.translate(x+size/2,y+size/2);ctx.fillStyle=p.m.color;ctx.strokeStyle='#0f172a';ctx.lineWidth=3;ctx.beginPath();roundRect(ctx,-size/2,-size/2,size,size,14);ctx.fill();ctx.stroke();ctx.fillStyle='rgba(255,255,255,.32)';ctx.beginPath();ctx.arc(-size*.16,-size*.08,size*.16,0,Math.PI*2);ctx.fill();ctx.fillStyle='#0f172a';ctx.font='900 24px sans-serif';ctx.fillText('🚢',-16,10);ctx.restore();ctx.fillStyle='#0f172a';ctx.font='800 18px sans-serif';ctx.fillText('ρ物平均 '+round(p.avg)+' / ρ液 '+p.l.rho+' / 比值 '+round(p.ratio),70,462);if(state.flash>0){ctx.fillStyle='rgba(250,204,21,'+(state.flash/20*.45)+')';ctx.fillRect(0,0,w,h);state.flash--}requestAnimationFrame(draw)}
  function render(){var lv=levels[state.level],p=params();$('levelNo').innerHTML=state.level+1;$('score').innerHTML=state.score;$('combo').innerHTML=state.combo;$('time').innerHTML=state.time;$('targetText').innerHTML=lv.title;$('storyText').innerHTML=lv.story;$('badge').innerHTML='目标：'+zoneName(lv.zone);$('volumeVal').innerHTML=$('volume').value;$('hollowVal').innerHTML=$('hollow').value;$('densityText').innerHTML=round(p.avg)+' / '+p.l.rho;$('densityBar').style.marginLeft=clamp(p.ratio/2*100,0,96)+'%';$('quickTip').innerHTML=p.ratio<.92?'现在偏轻：很容易上浮。':p.ratio>1.10?'现在偏重：会向下沉。':'接近平衡：有机会悬浮！';stars()}
  function start(){clearInterval(state.timer);state.started=true;state.score=0;state.combo=0;state.time=60;state.level=0;state.log=[];setPreset(0);$('log').innerHTML='<li>救援开始！连续成功会加分。</li>';$('feedback').className='feedback warn';$('feedback').innerHTML='救援开始：调参数后点“试一试”。';state.timer=setInterval(function(){state.time--;if(state.time<=0){clearInterval(state.timer);state.started=false;$('feedback').className='feedback warn';$('feedback').innerHTML='时间到！最终得分 '+state.score+'，星级 '+$('stars').innerHTML+'。'}render()},1000);render()}
  function addLog(t){state.log.unshift(t);state.log=state.log.slice(0,6);var ul=$('log');ul.innerHTML='';for(var i=0;i<state.log.length;i++){var li=document.createElement('li');li.appendChild(document.createTextNode(state.log[i]));ul.appendChild(li)}}
  function tryIt(){if(!state.started)start();var p=params(),lv=levels[state.level],r=targetRange(lv.zone),ok=p.y>=r[0]&&p.y<=r[1],near=Math.abs(p.y-(r[0]+r[1])/2);if(ok){var gain=50+state.combo*10+Math.max(0,Math.round((.2-near)*100));state.score+=gain;state.combo++;state.flash=20;$('feedback').className='feedback ok';$('feedback').innerHTML='成功！潜艇进入'+zoneName(lv.zone)+'，+'+gain+'分。物理原因：密度比 '+round(p.ratio)+' 决定上浮/悬浮/下沉。';addLog('第'+(state.level+1)+'关成功：'+lv.title+'（+'+gain+'）');if(state.level<levels.length-1){state.level++;setPreset(state.level)}else{clearInterval(state.timer);state.started=false;$('feedback').innerHTML+=' 全部救援完成！'}}else{state.combo=0;var dir=p.y<r[0]?'太浮了，增加密度或减少空心。':'太沉了，降低密度或增加空心/换高密度液体。';$('feedback').className='feedback bad';$('feedback').innerHTML='差一点：'+dir+' 当前密度比 '+round(p.ratio)+'。';addLog('第'+(state.level+1)+'关未成功：'+dir)}render()}
  function next(){state.level=(state.level+1)%levels.length;setPreset(state.level);state.combo=0;$('feedback').className='feedback';$('feedback').innerHTML='已切换关卡，看看目标区在哪里。';render()}
  function randomChallenge(){state.level=Math.floor(Math.random()*levels.length);setPreset(state.level);$('material').value=Object.keys(materials)[Math.floor(Math.random()*5)];$('liquid').value=Object.keys(liquids)[Math.floor(Math.random()*4)];$('hollow').value=Math.floor(Math.random()*89);$('volume').value=60+Math.floor(Math.random()*161);$('feedback').className='feedback warn';$('feedback').innerHTML='随机挑战来了！把潜艇调进目标区。';render()}
  $('startBtn').onclick=start;$('tryBtn').onclick=tryIt;$('nextBtn').onclick=next;$('randomBtn').onclick=randomChallenge;['material','liquid'].forEach(function(id){$(id).onchange=render});['volume','hollow'].forEach(function(id){$(id).oninput=render});setPreset(0);render();draw();
})();
