(function(){
  var materials={wood:{name:'木头',rho:.60,color:'#b7791f'},ice:{name:'冰块',rho:.92,color:'#bfdbfe'},plastic:{name:'塑料',rho:1.10,color:'#f97316'},brick:{name:'砖块',rho:1.80,color:'#b91c1c'},iron:{name:'铁块',rho:7.80,color:'#475569'}};
  var liquids={oil:{name:'食用油',rho:.80,color:'rgba(250,204,21,.52)'},water:{name:'清水',rho:1.00,color:'rgba(14,165,233,.45)'},salt:{name:'盐水',rho:1.20,color:'rgba(6,182,212,.50)'},honey:{name:'蜂蜜',rho:1.40,color:'rgba(245,158,11,.55)'}};
  var levels=[
    {want:'float',title:'让物体漂浮在水面上',hint:'物体平均密度小于液体密度，就会漂浮。'},
    {want:'sink',title:'让物体沉到水底',hint:'物体平均密度大于液体密度很多，浮力托不住重力。'},
    {want:'near',title:'做出接近悬浮的状态',hint:'让物体平均密度尽量接近液体密度。'},
    {want:'float',title:'用“空心”让较重材料浮起来',hint:'空心会降低平均密度，大船就是这个思路。'},
    {want:'sink',title:'换一种液体，判断谁更容易下沉',hint:'液体密度越大，能提供的浮力越强。'},
    {want:'near',title:'挑战：让物体停在水中间附近',hint:'密度越接近，越像悬浮。'}
  ];
  var state={level:0,score:0,last:null,anim:0};
  var $=function(id){return document.getElementById(id)};
  var canvas=$('scene'),ctx=canvas.getContext('2d');
  function getParams(){var m=materials[$('material').value],l=liquids[$('liquid').value],v=parseInt($('volume').value,10),h=parseInt($('hollow').value,10)/100;var avg=m.rho*(1-h);var ratio=avg/l.rho;var status=ratio<.97?'float':(ratio>1.05?'sink':'near');var submerged=Math.max(.12,Math.min(1,ratio));return{m:m,l:l,v:v,h:h,avg:avg,ratio:ratio,status:status,submerged:submerged};}
  function round(n){return Math.round(n*100)/100}
  function draw(p,drop){var w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#ecfeff';ctx.fillRect(0,0,w,h);ctx.fillStyle='#0f172a';ctx.font='700 22px sans-serif';ctx.fillText('浮力实验水槽',28,38);var tank={x:76,y:82,w:568,h:340};ctx.strokeStyle='#155e75';ctx.lineWidth=5;ctx.strokeRect(tank.x,tank.y,tank.w,tank.h);var waterY=tank.y+92;ctx.fillStyle=p.l.color;ctx.fillRect(tank.x+3,waterY,tank.w-6,tank.h-3-(waterY-tank.y));ctx.fillStyle='rgba(255,255,255,.45)';for(var i=0;i<8;i++){ctx.beginPath();ctx.arc(tank.x+40+i*68,waterY+12+Math.sin((state.anim+i)/9)*5,18,0,Math.PI*2);ctx.fill()}var size=62+Math.round((p.v-60)/160*44);var x=tank.x+tank.w/2-size/2;var targetY;if(p.status==='float'){targetY=waterY-size*(1-p.submerged)}else if(p.status==='near'){targetY=waterY+128}else{targetY=tank.y+tank.h-size-4}var y=drop?tank.y+12+(targetY-(tank.y+12))*drop:targetY;ctx.fillStyle=p.m.color;ctx.strokeStyle='#0f172a';ctx.lineWidth=3;ctx.fillRect(x,y,size,size);ctx.strokeRect(x,y,size,size);ctx.fillStyle='rgba(255,255,255,.25)';ctx.fillRect(x+10,y+10,size-20,12);ctx.font='800 18px sans-serif';ctx.fillStyle='#0f172a';ctx.fillText(p.m.name,x+8,y+size/2+6);ctx.strokeStyle='#ef4444';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(x+size+34,y+size/2-30);ctx.lineTo(x+size+34,y+size/2+30);ctx.stroke();ctx.fillStyle='#ef4444';ctx.beginPath();ctx.moveTo(x+size+34,y+size/2+36);ctx.lineTo(x+size+24,y+size/2+18);ctx.lineTo(x+size+44,y+size/2+18);ctx.fill();ctx.fillStyle='#ef4444';ctx.font='800 18px sans-serif';ctx.fillText('G',x+size+48,y+size/2+8);ctx.strokeStyle='#16a34a';ctx.beginPath();ctx.moveTo(x-28,y+size/2+30);ctx.lineTo(x-28,y+size/2-30);ctx.stroke();ctx.fillStyle='#16a34a';ctx.beginPath();ctx.moveTo(x-28,y+size/2-36);ctx.lineTo(x-38,y+size/2-18);ctx.lineTo(x-18,y+size/2-18);ctx.fill();ctx.font='800 18px sans-serif';ctx.fillText('F浮',x-68,y+size/2+8);ctx.fillStyle='#0f172a';ctx.font='700 18px sans-serif';ctx.fillText('液体：'+p.l.name+' ρ='+p.l.rho+' g/cm³',96,454);ctx.fillText('物体平均密度：'+round(p.avg)+' g/cm³',350,454)}
  function renderList(){var ul=$('levelList');ul.innerHTML='';for(var i=0;i<levels.length;i++){var li=document.createElement('li');li.className=i===state.level?'active':'';li.appendChild(document.createTextNode((i+1)+'. '+levels[i].title));ul.appendChild(li)}}
  function render(){var lv=levels[state.level];$('levelNo').innerHTML=state.level+1;$('targetText').innerHTML=lv.title;$('hintText').innerHTML=lv.hint;$('score').innerHTML=state.score;$('volumeVal').innerHTML=$('volume').value;$('hollowVal').innerHTML=$('hollow').value;var p=getParams();$('numbers').innerHTML='ρ物平均='+round(p.avg)+'，ρ液='+p.l.rho+'；密度比='+round(p.ratio)+'。';draw(p,1);renderList()}
  function explain(p){var fb='最大浮力约等于 ρ液×g×V = '+p.l.rho+'×g×'+p.v;var g='重力约等于 ρ物×g×V = '+round(p.avg)+'×g×'+p.v;var text=p.status==='float'?'结果：漂浮。只有一部分浸入液体，浮力就能等于重力。':(p.status==='sink'?'结果：下沉。完全浸没后，最大浮力仍小于重力。':'结果：接近悬浮。浮力和重力很接近，物体会停在液体中部附近。');return text+' '+fb+'；'+g+'。'}
  function run(){var p=getParams(),lv=levels[state.level],ok=false;if(lv.want==='near'){ok=Math.abs(p.ratio-1)<=.08}else{ok=p.status===lv.want}var t=0;function step(){t+=.045;draw(p,Math.min(1,t));if(t<1){requestAnimationFrame(step)}else{var msg=explain(p);if(ok){state.score+=20;$('result').innerHTML='闯关成功！'+msg+' +20分'}else{$('result').innerHTML='还差一点：目标是“'+lv.title+'”。'+msg} $('score').innerHTML=state.score}}requestAnimationFrame(step)}
  function next(){state.level=(state.level+1)%levels.length;$('result').innerHTML='新目标已出现，先调参数再开始实验。';render()}
  $('runBtn').onclick=run;$('nextBtn').onclick=next;$('material').onchange=render;$('liquid').onchange=render;$('volume').oninput=render;$('hollow').oninput=render;render();
})();
