(function(){
  var KEY='stress-meter-v1';
  var questions=[
    ['今天学习任务让我觉得有压力','study'],['考试/成绩让我担心','study'],['和同学朋友相处有点累','social'],['家里沟通或期待让我紧张','family'],['睡眠或身体疲劳影响状态','body'],['手机/游戏/消息让我难专注','focus'],['我觉得事情太多不知道先做什么','study'],['我愿意主动求助或说出来','protect']
  ];
  var names={study:'学习任务',social:'人际关系',family:'家庭沟通',body:'身体疲劳',focus:'专注干扰',protect:'求助保护'};
  function $(id){return document.getElementById(id)}
  function esc(s){return String(s).replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]})}
  function today(){var d=new Date();return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())} function pad(n){return n<10?'0'+n:''+n}
  function load(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch(e){return []}} function save(list){localStorage.setItem(KEY,JSON.stringify(list.slice(0,14)))}
  function renderQuiz(){var box=$('quiz'), html=''; for(var i=0;i<questions.length;i++){html+='<div class="q"><div class="q-title">'+(i+1)+'. '+questions[i][0]+'</div><div class="choices">'; for(var v=0;v<4;v++){html+='<label><input type="radio" name="q'+i+'" value="'+v+'" '+(v===0?'checked':'')+'> '+['没有','一点','明显','很多'][v]+'</label>'} html+='</div></div>'} box.innerHTML=html; var inputs=box.getElementsByTagName('input'); for(i=0;i<inputs.length;i++)inputs[i].onchange=update}
  function calc(){var score=0, src={study:0,social:0,family:0,body:0,focus:0,protect:0}; for(var i=0;i<questions.length;i++){var el=document.querySelector('input[name="q'+i+'"]:checked'), v=parseInt(el&&el.value||0,10); if(questions[i][1]==='protect')v=3-v; score+=v; src[questions[i][1]]+=v} return {score:score,src:src}}
  function topSource(src){var best='study',val=-1; for(var k in src){if(k!=='protect'&&src[k]>val){best=k;val=src[k]}} return names[best]||'学习任务'}
  function advice(score,source){var arr=[]; if(score<=7){arr=['保持现在的节奏，今天完成一个最重要的小任务就很好。','睡前给自己一句肯定：我已经在努力，也允许慢慢来。','继续保留运动、喝水、早睡中的一个好习惯。']} else if(score<=15){arr=['先写下 3 件事，只选最容易的 1 件开始，完成后再看下一件。','做 3 分钟慢呼吸或伸展，让身体先从紧绷里出来。','把“我担心……”告诉一位家人或老师，请他帮你一起排顺序。']} else {arr=['今天先暂停自责，找可信任的大人说一句：我压力很高，需要帮忙。','把任务减少到“必须做的一小步”，其余先放进明日清单。','若持续失眠、胸闷、哭泣或影响生活，请尽快联系家人、老师或专业人士。']} if(source==='身体疲劳')arr[0]='先补水、吃点东西或休息 10 分钟，身体恢复后再处理任务。'; if(source==='专注干扰')arr[0]='把手机放到看不见的地方 15 分钟，只做一道题或一页书。'; return arr}
  function update(){var r=calc(), pct=Math.round(r.score/24*100), source=topSource(r.src), cls=r.score<=7?'calm':(r.score<=15?'watch':'high'), text=r.score<=7?'轻压力：状态较稳':(r.score<=15?'中压力：需要调节':'高压力：建议求助'); $('bar').style.width=pct+'%'; $('scoreText').innerHTML=r.score+' / 24'; $('level').className='level '+cls; $('level').innerHTML=text; $('source').innerHTML='当前最明显来源：<b>'+source+'</b>'; var arr=advice(r.score,source); $('advice').innerHTML='<ol><li>'+arr.join('</li><li>')+'</li></ol>'}
  function renderHistory(){var list=load(), box=$('historyList'); if(!list.length){box.innerHTML='<p class="source">暂无记录。保存后只会留在当前浏览器本机。</p>';return} box.innerHTML=''; for(var i=0;i<list.length;i++){var d=document.createElement('div');d.className='record';d.innerHTML='<b>'+esc(list[i].date)+'</b> · '+esc(list[i].score)+'/24 · '+esc(list[i].source);box.appendChild(d)}}
  document.addEventListener('DOMContentLoaded',function(){renderQuiz(); update(); renderHistory(); $('saveBtn').onclick=function(){var r=calc(), s=topSource(r.src), list=load(), item={date:today(),score:r.score,source:s}; var out=[item]; for(var i=0;i<list.length;i++){if(list[i].date!==item.date)out.push(list[i])} save(out); renderHistory(); alert('已保存到本机浏览器。')}; $('resetBtn').onclick=function(){renderQuiz();update()}; var tools=document.querySelectorAll('.tool'); for(var i=0;i<tools.length;i++){tools[i].onclick=function(){for(var j=0;j<tools.length;j++)tools[j].className='tool';this.className='tool active';$('toolTip').innerHTML=this.getAttribute('data-tip')}}});
})();
